USE [SHOESHOP]
GO
/****** Object:  Table [dbo].[CARGO]    Script Date: 05/17/2012 14:24:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CARGO](
	[CargoID] [int] IDENTITY(1,1) NOT NULL,
	[CargoName] [nvarchar](50) NULL,
	[CargoPrice] [decimal](18, 0) NULL,
 CONSTRAINT [PK_CARGO] PRIMARY KEY CLUSTERED 
(
	[CargoID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCER]    Script Date: 05/17/2012 14:24:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCER](
	[ProducerID] [int] NOT NULL,
	[ProducerName] [nvarchar](max) NOT NULL,
	[Phone] [nvarchar](max) NULL,
	[Email] [nvarchar](max) NOT NULL,
	[Date] [datetime] NOT NULL,
	[Description] [text] NULL,
 CONSTRAINT [PK_PRODUCER_1] PRIMARY KEY CLUSTERED 
(
	[ProducerID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PERSON]    Script Date: 05/17/2012 14:24:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[PERSON](
	[Pno] [int] NOT NULL,
	[Name] [varchar](25) NOT NULL,
	[Surname] [varchar](25) NOT NULL,
	[Email] [nvarchar](max) NOT NULL,
	[Password] [nvarchar](max) NOT NULL,
	[Date] [datetime] NOT NULL,
 CONSTRAINT [PK_PERSON_1] PRIMARY KEY CLUSTERED 
(
	[Pno] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[PAYMENTTYPE]    Script Date: 05/17/2012 14:24:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAYMENTTYPE](
	[PaymentTypeID] [int] IDENTITY(1,1) NOT NULL,
	[PaymentTypeName] [nvarchar](50) NULL,
	[PaymentTypeInfo] [nvarchar](max) NULL,
 CONSTRAINT [PK_PAYMENTTYPE] PRIMARY KEY CLUSTERED 
(
	[PaymentTypeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CITY]    Script Date: 05/17/2012 14:24:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CITY](
	[CityID] [int] NOT NULL,
	[CityCode] [int] NOT NULL,
	[CityName] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_CITY] PRIMARY KEY CLUSTERED 
(
	[CityID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CAMPAIGN]    Script Date: 05/17/2012 14:24:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CAMPAIGN](
	[CampaignID] [int] IDENTITY(1,1) NOT NULL,
	[CampaignName] [nvarchar](50) NULL,
	[CampaignRate] [decimal](18, 0) NULL,
	[CampaignStartDate] [datetime] NULL,
	[CampaignFinishDate] [datetime] NULL,
 CONSTRAINT [PK_CAMPAIGN] PRIMARY KEY CLUSTERED 
(
	[CampaignID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ADMIN]    Script Date: 05/17/2012 14:24:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADMIN](
	[Pno] [int] NOT NULL,
	[LastLogin] [datetime] NULL,
 CONSTRAINT [PK_ADMIN] PRIMARY KEY CLUSTERED 
(
	[Pno] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCT]    Script Date: 05/17/2012 14:24:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCT](
	[ProductID] [int] NOT NULL,
	[ProducerID] [int] NOT NULL,
	[Model] [nchar](10) NOT NULL,
	[Type] [int] NOT NULL,
	[Sex] [int] NOT NULL,
	[Description] [nvarchar](max) NULL,
	[ImportDate] [datetime] NOT NULL,
 CONSTRAINT [PK_PRODUCT] PRIMARY KEY CLUSTERED 
(
	[ProductID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DISTRICT]    Script Date: 05/17/2012 14:24:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DISTRICT](
	[DistrictID] [int] NOT NULL,
	[CityCode] [int] NOT NULL,
	[DistrictCode] [int] NOT NULL,
	[DistrictName] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_DISTRICT] PRIMARY KEY CLUSTERED 
(
	[DistrictID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHONE]    Script Date: 05/17/2012 14:24:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHONE](
	[PhoneID] [int] NOT NULL,
	[Pno] [int] NOT NULL,
	[AreaCode] [nvarchar](max) NOT NULL,
	[PhoneNumber] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_PHONE] PRIMARY KEY CLUSTERED 
(
	[PhoneID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CAMPAIGNPRODUCT]    Script Date: 05/17/2012 14:24:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CAMPAIGNPRODUCT](
	[CampaignProduct] [int] IDENTITY(1,1) NOT NULL,
	[CampaignID] [int] NULL,
	[ProductID] [int] NULL,
 CONSTRAINT [PK_CAMPAIGNPRODUCT] PRIMARY KEY CLUSTERED 
(
	[CampaignProduct] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CUSTOMER]    Script Date: 05/17/2012 14:24:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CUSTOMER](
	[Pno] [int] NOT NULL,
	[Age] [int] NOT NULL,
	[LastProcessDate] [datetime] NULL,
	[LastItemID] [int] NULL,
 CONSTRAINT [PK_CUSTOMER] PRIMARY KEY CLUSTERED 
(
	[Pno] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INVENTORY]    Script Date: 05/17/2012 14:24:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INVENTORY](
	[ProductID] [int] NOT NULL,
	[Count] [int] NOT NULL,
	[LastUpdate] [datetime] NOT NULL,
	[PricePerPiece] [float] NOT NULL,
 CONSTRAINT [PK_INVENTORY] PRIMARY KEY CLUSTERED 
(
	[ProductID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ADDRESS]    Script Date: 05/17/2012 14:24:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ADDRESS](
	[AddressID] [int] NOT NULL,
	[Pno] [int] NOT NULL,
	[CityID] [int] NOT NULL,
	[DistrictID] [int] NOT NULL,
	[BuildingNum] [nvarchar](max) NOT NULL,
	[DoorNum] [nvarchar](max) NOT NULL,
	[PostalCode] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_ADDRESS] PRIMARY KEY CLUSTERED 
(
	[AddressID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CARTPRODUCT]    Script Date: 05/17/2012 14:24:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CARTPRODUCT](
	[CartProductID] [int] IDENTITY(1,1) NOT NULL,
	[Pno] [int] NULL,
	[ProductID] [int] NULL,
 CONSTRAINT [PK_CARTPRODUCT] PRIMARY KEY CLUSTERED 
(
	[CartProductID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SALE]    Script Date: 05/17/2012 14:24:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SALE](
	[SaleID] [int] IDENTITY(1,1) NOT NULL,
	[Pno] [int] NULL,
	[AddressID] [int] NULL,
	[CargoID] [int] NULL,
	[PaymentTypeID] [int] NULL,
 CONSTRAINT [PK_SALE] PRIMARY KEY CLUSTERED 
(
	[SaleID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SALEPRODUCT]    Script Date: 05/17/2012 14:24:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SALEPRODUCT](
	[SaleProductID] [int] IDENTITY(1,1) NOT NULL,
	[SaleID] [int] NULL,
	[ProductID] [int] NULL,
 CONSTRAINT [PK_SALEPRODUCT_1] PRIMARY KEY CLUSTERED 
(
	[SaleProductID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  ForeignKey [FK_ADDRESS_CITY]    Script Date: 05/17/2012 14:24:41 ******/
ALTER TABLE [dbo].[ADDRESS]  WITH CHECK ADD  CONSTRAINT [FK_ADDRESS_CITY] FOREIGN KEY([CityID])
REFERENCES [dbo].[CITY] ([CityID])
GO
ALTER TABLE [dbo].[ADDRESS] CHECK CONSTRAINT [FK_ADDRESS_CITY]
GO
/****** Object:  ForeignKey [FK_ADDRESS_DISTRICT]    Script Date: 05/17/2012 14:24:41 ******/
ALTER TABLE [dbo].[ADDRESS]  WITH CHECK ADD  CONSTRAINT [FK_ADDRESS_DISTRICT] FOREIGN KEY([DistrictID])
REFERENCES [dbo].[DISTRICT] ([DistrictID])
GO
ALTER TABLE [dbo].[ADDRESS] CHECK CONSTRAINT [FK_ADDRESS_DISTRICT]
GO
/****** Object:  ForeignKey [FK_ADDRESS_PERSON]    Script Date: 05/17/2012 14:24:41 ******/
ALTER TABLE [dbo].[ADDRESS]  WITH CHECK ADD  CONSTRAINT [FK_ADDRESS_PERSON] FOREIGN KEY([Pno])
REFERENCES [dbo].[PERSON] ([Pno])
GO
ALTER TABLE [dbo].[ADDRESS] CHECK CONSTRAINT [FK_ADDRESS_PERSON]
GO
/****** Object:  ForeignKey [FK_ADMIN_PERSON]    Script Date: 05/17/2012 14:24:41 ******/
ALTER TABLE [dbo].[ADMIN]  WITH CHECK ADD  CONSTRAINT [FK_ADMIN_PERSON] FOREIGN KEY([Pno])
REFERENCES [dbo].[PERSON] ([Pno])
GO
ALTER TABLE [dbo].[ADMIN] CHECK CONSTRAINT [FK_ADMIN_PERSON]
GO
/****** Object:  ForeignKey [FK_CAMPAIGNPRODUCT_CAMPAIGN]    Script Date: 05/17/2012 14:24:41 ******/
ALTER TABLE [dbo].[CAMPAIGNPRODUCT]  WITH CHECK ADD  CONSTRAINT [FK_CAMPAIGNPRODUCT_CAMPAIGN] FOREIGN KEY([CampaignID])
REFERENCES [dbo].[CAMPAIGN] ([CampaignID])
GO
ALTER TABLE [dbo].[CAMPAIGNPRODUCT] CHECK CONSTRAINT [FK_CAMPAIGNPRODUCT_CAMPAIGN]
GO
/****** Object:  ForeignKey [FK_CAMPAIGNPRODUCT_PRODUCT]    Script Date: 05/17/2012 14:24:41 ******/
ALTER TABLE [dbo].[CAMPAIGNPRODUCT]  WITH CHECK ADD  CONSTRAINT [FK_CAMPAIGNPRODUCT_PRODUCT] FOREIGN KEY([ProductID])
REFERENCES [dbo].[PRODUCT] ([ProductID])
GO
ALTER TABLE [dbo].[CAMPAIGNPRODUCT] CHECK CONSTRAINT [FK_CAMPAIGNPRODUCT_PRODUCT]
GO
/****** Object:  ForeignKey [FK_CARTPRODUCT_CUSTOMER]    Script Date: 05/17/2012 14:24:41 ******/
ALTER TABLE [dbo].[CARTPRODUCT]  WITH CHECK ADD  CONSTRAINT [FK_CARTPRODUCT_CUSTOMER] FOREIGN KEY([Pno])
REFERENCES [dbo].[CUSTOMER] ([Pno])
GO
ALTER TABLE [dbo].[CARTPRODUCT] CHECK CONSTRAINT [FK_CARTPRODUCT_CUSTOMER]
GO
/****** Object:  ForeignKey [FK_CARTPRODUCT_PRODUCT]    Script Date: 05/17/2012 14:24:41 ******/
ALTER TABLE [dbo].[CARTPRODUCT]  WITH CHECK ADD  CONSTRAINT [FK_CARTPRODUCT_PRODUCT] FOREIGN KEY([ProductID])
REFERENCES [dbo].[PRODUCT] ([ProductID])
GO
ALTER TABLE [dbo].[CARTPRODUCT] CHECK CONSTRAINT [FK_CARTPRODUCT_PRODUCT]
GO
/****** Object:  ForeignKey [FK_CUSTOMER_PERSON]    Script Date: 05/17/2012 14:24:41 ******/
ALTER TABLE [dbo].[CUSTOMER]  WITH CHECK ADD  CONSTRAINT [FK_CUSTOMER_PERSON] FOREIGN KEY([Pno])
REFERENCES [dbo].[PERSON] ([Pno])
GO
ALTER TABLE [dbo].[CUSTOMER] CHECK CONSTRAINT [FK_CUSTOMER_PERSON]
GO
/****** Object:  ForeignKey [FK_CUSTOMER_PRODUCT]    Script Date: 05/17/2012 14:24:41 ******/
ALTER TABLE [dbo].[CUSTOMER]  WITH CHECK ADD  CONSTRAINT [FK_CUSTOMER_PRODUCT] FOREIGN KEY([LastItemID])
REFERENCES [dbo].[PRODUCT] ([ProductID])
GO
ALTER TABLE [dbo].[CUSTOMER] CHECK CONSTRAINT [FK_CUSTOMER_PRODUCT]
GO
/****** Object:  ForeignKey [FK_DISTRICT_CITY]    Script Date: 05/17/2012 14:24:41 ******/
ALTER TABLE [dbo].[DISTRICT]  WITH CHECK ADD  CONSTRAINT [FK_DISTRICT_CITY] FOREIGN KEY([CityCode])
REFERENCES [dbo].[CITY] ([CityID])
GO
ALTER TABLE [dbo].[DISTRICT] CHECK CONSTRAINT [FK_DISTRICT_CITY]
GO
/****** Object:  ForeignKey [FK_INVENTORY_PRODUCT]    Script Date: 05/17/2012 14:24:41 ******/
ALTER TABLE [dbo].[INVENTORY]  WITH CHECK ADD  CONSTRAINT [FK_INVENTORY_PRODUCT] FOREIGN KEY([ProductID])
REFERENCES [dbo].[PRODUCT] ([ProductID])
GO
ALTER TABLE [dbo].[INVENTORY] CHECK CONSTRAINT [FK_INVENTORY_PRODUCT]
GO
/****** Object:  ForeignKey [FK_PHONE_PERSON]    Script Date: 05/17/2012 14:24:41 ******/
ALTER TABLE [dbo].[PHONE]  WITH CHECK ADD  CONSTRAINT [FK_PHONE_PERSON] FOREIGN KEY([Pno])
REFERENCES [dbo].[PERSON] ([Pno])
GO
ALTER TABLE [dbo].[PHONE] CHECK CONSTRAINT [FK_PHONE_PERSON]
GO
/****** Object:  ForeignKey [FK_PRODUCT_PRODUCER]    Script Date: 05/17/2012 14:24:41 ******/
ALTER TABLE [dbo].[PRODUCT]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCT_PRODUCER] FOREIGN KEY([ProducerID])
REFERENCES [dbo].[PRODUCER] ([ProducerID])
GO
ALTER TABLE [dbo].[PRODUCT] CHECK CONSTRAINT [FK_PRODUCT_PRODUCER]
GO
/****** Object:  ForeignKey [FK_SALE_ADDRESS]    Script Date: 05/17/2012 14:24:41 ******/
ALTER TABLE [dbo].[SALE]  WITH CHECK ADD  CONSTRAINT [FK_SALE_ADDRESS] FOREIGN KEY([AddressID])
REFERENCES [dbo].[ADDRESS] ([AddressID])
GO
ALTER TABLE [dbo].[SALE] CHECK CONSTRAINT [FK_SALE_ADDRESS]
GO
/****** Object:  ForeignKey [FK_SALE_CARGO]    Script Date: 05/17/2012 14:24:41 ******/
ALTER TABLE [dbo].[SALE]  WITH CHECK ADD  CONSTRAINT [FK_SALE_CARGO] FOREIGN KEY([CargoID])
REFERENCES [dbo].[CARGO] ([CargoID])
GO
ALTER TABLE [dbo].[SALE] CHECK CONSTRAINT [FK_SALE_CARGO]
GO
/****** Object:  ForeignKey [FK_SALE_CUSTOMER]    Script Date: 05/17/2012 14:24:41 ******/
ALTER TABLE [dbo].[SALE]  WITH CHECK ADD  CONSTRAINT [FK_SALE_CUSTOMER] FOREIGN KEY([Pno])
REFERENCES [dbo].[CUSTOMER] ([Pno])
GO
ALTER TABLE [dbo].[SALE] CHECK CONSTRAINT [FK_SALE_CUSTOMER]
GO
/****** Object:  ForeignKey [FK_SALE_PAYMENTTYPE]    Script Date: 05/17/2012 14:24:41 ******/
ALTER TABLE [dbo].[SALE]  WITH CHECK ADD  CONSTRAINT [FK_SALE_PAYMENTTYPE] FOREIGN KEY([PaymentTypeID])
REFERENCES [dbo].[PAYMENTTYPE] ([PaymentTypeID])
GO
ALTER TABLE [dbo].[SALE] CHECK CONSTRAINT [FK_SALE_PAYMENTTYPE]
GO
/****** Object:  ForeignKey [FK_SALEPRODUCT_PRODUCT]    Script Date: 05/17/2012 14:24:41 ******/
ALTER TABLE [dbo].[SALEPRODUCT]  WITH CHECK ADD  CONSTRAINT [FK_SALEPRODUCT_PRODUCT] FOREIGN KEY([ProductID])
REFERENCES [dbo].[PRODUCT] ([ProductID])
GO
ALTER TABLE [dbo].[SALEPRODUCT] CHECK CONSTRAINT [FK_SALEPRODUCT_PRODUCT]
GO
/****** Object:  ForeignKey [FK_SALEPRODUCT_SALE]    Script Date: 05/17/2012 14:24:41 ******/
ALTER TABLE [dbo].[SALEPRODUCT]  WITH CHECK ADD  CONSTRAINT [FK_SALEPRODUCT_SALE] FOREIGN KEY([SaleID])
REFERENCES [dbo].[SALE] ([SaleID])
GO
ALTER TABLE [dbo].[SALEPRODUCT] CHECK CONSTRAINT [FK_SALEPRODUCT_SALE]
GO
